apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      prometheus:
        config:
          scrape_configs:
            - job_name: envoy
              static_configs:
                - targets: ['envoy.default.svc.cluster.local:9901']

    processors:
      batch:

    exporters:
      logging:
        loglevel: debug

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]

        metrics:
          receivers: [prometheus]
          processors: [batch]
          exporters: [logging]

        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]

